# Generated by Django 3.2.6 on 2021-10-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_rename_sugeestedcategory_suggestedcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='flagReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Q', 'Questions'), ('A', 'Answers'), ('U', 'Users')], max_length=1)),
                ('nameEN', models.CharField(max_length=50)),
                ('nameAR', models.CharField(max_length=50)),
                ('descEN', models.CharField(max_length=300)),
                ('descAR', models.CharField(max_length=300)),
            ],
        ),
    ]
