# Generated by Django 3.2.6 on 2021-10-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_postreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreport',
            old_name='report',
            new_name='reporter',
        ),
    ]
