# Generated by Django 3.2.6 on 2021-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_tag'),
        ('authusers', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(null=True, to='content.Tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
