# Generated by Django 3.2.6 on 2021-09-06 10:33

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0007_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='E:\\projects\\interviewsquestion\\back-end\\media\\profile/default.jpg', upload_to=pathlib.PureWindowsPath('E:/projects/interviewsquestion/back-end/media/profile')),
        ),
    ]
