# Generated by Django 3.2.6 on 2021-09-06 17:48

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permission',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('A', 'Admin'), ('M', 'Moderator'), ('U', 'User')], default='U', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to=pathlib.PureWindowsPath('E:/projects/interviewsquestion/back-end/media/profile')),
        ),
    ]
