# Generated by Django 3.2.6 on 2021-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0009_auto_20210906_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='socialID',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
