# Generated by Django 3.2.6 on 2021-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0010_userprofile_socialid'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.URLField()),
                ('socialID', models.CharField(max_length=150, unique=True)),
                ('provider', models.CharField(choices=[('fa', 'Facebook'), ('tw', 'Twitter'), ('go', 'Google'), ('gi', 'Github')], max_length=20)),
            ],
        ),
    ]
