# Generated by Django 3.2.6 on 2021-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0011_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='fullName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together={('provider', 'socialID')},
        ),
    ]
