# Generated by Django 3.2.6 on 2021-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0012_auto_20210910_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(choices=[('fa', 'Facebook'), ('tw', 'Twitter'), ('go', 'Google'), ('gi', 'Github')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='socialID',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
