# Generated by Django 3.2.6 on 2021-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_badge'),
        ('authusers', '0016_auto_20210925_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(to='content.Badge'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
