# Generated by Django 3.2.6 on 2021-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0017_auto_20210926_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
