# Generated by Django 3.2.6 on 2021-09-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_badge_reason'),
        ('authusers', '0018_auto_20210927_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.CreateModel(
            name='BadgesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authusers.userprofile')),
            ],
        ),
    ]
