# Generated by Django 3.2.6 on 2021-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_badge_reason'),
        ('authusers', '0019_auto_20210928_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(through='authusers.BadgesUser', to='content.Badge'),
        ),
    ]
