# Generated by Django 3.2.6 on 2021-09-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0020_userprofile_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgesuser',
            options={'ordering': ['date']},
        ),
    ]
