# Generated by Django 3.2.6 on 2021-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0022_userprofile_lastactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastActive',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
