# Generated by Django 3.2.6 on 2021-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0024_auto_20210930_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('ar', 'عربي'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
