# Generated by Django 3.2.6 on 2021-10-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_badge_reason'),
        ('authusers', '0025_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
    ]
