# Generated by Django 3.2.6 on 2021-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0027_auto_20211005_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loginTimes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
