# Generated by Django 3.2.6 on 2021-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0030_authlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlist',
            name='language',
            field=models.CharField(choices=[('ar', 'عربي'), ('en', 'English')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
