# Generated by Django 3.2.6 on 2021-10-14 14:49

from django.db import migrations

def addAuthPage(apps, schema_editor):
    model=apps.get_model('authusers','AuthList')
    model.objects.create(page='L',language='en',list='[]')
    model.objects.create(page='L',language='ar',list='[]')
    model.objects.create(page='R',language='en',list='[]')
    model.objects.create(page='R',language='ar',list='[]')

class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0031_authlist_language'),
    ]

    operations = [
        migrations.RunPython(addAuthPage)
    ]
