# Generated by Django 3.2.6 on 2021-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0031_auto_20211014_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlist',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
