# Generated by Django 3.2.6 on 2021-10-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0030_alter_badge_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ar', 'عربي'), ('en', 'English')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='polls', to='content.Category')),
                ('tags', models.ManyToManyField(related_name='polls', to='content.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Radio'), ('C', 'Check')], max_length=1)),
                ('options', models.JSONField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
        ),
    ]
