# Generated by Django 3.2.6 on 2021-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
