# Generated by Django 3.2.6 on 2021-10-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_isopened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitem',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='pollitem',
            name='type',
            field=models.CharField(choices=[('R', 'Radio List'), ('C', 'Check List')], max_length=1),
        ),
    ]
