# Generated by Django 3.2.6 on 2021-10-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_pollresault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresault',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resaults', to='polls.poll'),
        ),
    ]
