# Generated by Django 3.2.6 on 2021-10-06 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_alter_pollresault_poll'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollresault',
            unique_together={('poll', 'user')},
        ),
    ]
