# Generated by Django 3.2.6 on 2021-09-24 14:24

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Advertic With Us', max_length=30)),
                ('language', models.CharField(choices=[('AR', 'عربي'), ('EN', 'English')], max_length=2)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('AR', 'عربي'), ('EN', 'English')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(choices=[('AR', 'عربي'), ('EN', 'English')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('E:/projects/interviewsquestion/back-end/media/services'))),
                ('language', models.CharField(choices=[('AR', 'عربي'), ('EN', 'English')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFile', models.ImageField(upload_to=pathlib.PureWindowsPath('E:/projects/interviewsquestion/back-end/media/advertise'))),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.advertisepage')),
            ],
        ),
    ]
