# Generated by Django 3.2.6 on 2021-09-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_infoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=130)),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('AR', 'عربي'), ('EN', 'English')], default='EN', max_length=2)),
            ],
        ),
    ]
