# Generated by Django 3.2.6 on 2021-10-15 07:41

from django.db import migrations

def addTemrsPage(apps,editor):
    model=apps.get_model('misc','TermsPage')
    model.objects.create(language='en')
    model.objects.create(language='ar')
class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_termspage'),
    ]

    operations = [
        migrations.RunPython(addTemrsPage)
    ]
