# Generated by Django 3.2.6 on 2021-10-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_auto_20211015_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termspage',
            old_name='page',
            new_name='html',
        ),
    ]
