# Generated by Django 3.2.6 on 2021-09-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Q', 'Question'), ('A', 'Answer')], max_length=1)),
                ('isPublished', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.category')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='content.post')),
                ('tags', models.ManyToManyField(related_name='questions', to='content.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('A', 'Accept'), ('E', 'Edit'), ('AE', 'Accept Edit'), ('P', 'Publish'), ('UP', 'Unpublish')], max_length=4)),
                ('isAccepted', models.BooleanField(default=False)),
                ('acceptTime', models.TimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content.post')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
