# Generated by Django 3.2.6 on 2021-09-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_postlog_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlog',
            name='acceptTime',
        ),
        migrations.RemoveField(
            model_name='postlog',
            name='isAccepted',
        ),
        migrations.CreateModel(
            name='SuggestedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('tags', models.ManyToManyField(to='content.Tag')),
            ],
        ),
    ]
