# Generated by Django 3.2.6 on 2021-09-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_suggestedquestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlog',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.question'),
        ),
        migrations.AlterField(
            model_name='postlog',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='postlog',
            name='type',
            field=models.CharField(choices=[('S', 'Suggest'), ('A', 'Accept'), ('R', 'Reject'), ('E', 'Edit'), ('AE', 'Accept Edit'), ('P', 'Publish'), ('UP', 'Unpublish')], max_length=4),
        ),
    ]
