# Generated by Django 3.2.6 on 2021-09-14 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210914_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlog',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='postlog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
