# Generated by Django 3.2.6 on 2021-09-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210914_1213'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='content_pos_author__ebea4c_idx'),
        ),
    ]
