# Generated by Django 3.2.6 on 2021-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_post_content_pos_author__ebea4c_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postlog',
            index=models.Index(fields=['type', 'post'], name='content_pos_type_a87246_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='content_que_categor_5a559c_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestedquestion',
            index=models.Index(fields=['category'], name='content_sug_categor_0b8acd_idx'),
        ),
    ]
