# Generated by Django 3.2.6 on 2021-09-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlog',
            name='question',
        ),
        migrations.AddField(
            model_name='suggestedquestion',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.question'),
        ),
    ]
