# Generated by Django 3.2.6 on 2021-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='type',
            field=models.CharField(choices=[('S', 'Suggest'), ('A', 'Accept'), ('R', 'Reject'), ('SE', 'Suggest Edit'), ('AE', 'Accept Edit'), ('P', 'Publish'), ('UP', 'Unpublish')], max_length=4),
        ),
    ]
