# Generated by Django 3.2.6 on 2021-09-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_postlog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlog',
            name='title',
        ),
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='content.post'),
        ),
    ]
