# Generated by Django 3.2.6 on 2021-09-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20210918_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlog',
            name='originLog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.postlog'),
        ),
        migrations.AlterField(
            model_name='postlog',
            name='edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content.suggestededit'),
        ),
    ]
