# Generated by Django 3.2.6 on 2021-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20210921_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='default     description=models.TextField()'),
            preserve_default=False,
        ),
    ]
