# Generated by Django 3.2.6 on 2021-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_post_ispublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze')], max_length=1)),
                ('reason', models.CharField(choices=[('Q', 'Questions'), ('A', 'Answers'), ('SA', 'Self Answers'), ('C', 'Comments'), ('SC', 'Self Comments'), ('V', 'Views')], max_length=2)),
                ('targetType', models.CharField(choices=[('T', 'Tag'), ('C', 'Category'), ('G', 'General')], max_length=1)),
                ('count', models.IntegerField()),
                ('rep', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.category')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.tag')),
            ],
        ),
    ]
