# Generated by Django 3.2.6 on 2021-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_badge_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='reason',
            field=models.CharField(choices=[('Q', 'Questions'), ('A', 'Answers'), ('SA', 'Self Answers'), ('C', 'Comments'), ('SC', 'Self Comments'), ('V', 'Views'), ('PV', 'Post Votes'), ('QV', 'Question Votes'), ('AV', 'Answer Votes'), ('E', 'Edits')], max_length=2),
        ),
    ]
