# Generated by Django 3.2.6 on 2021-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_badge_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='reason',
            field=models.CharField(choices=[('Q', 'Questions'), ('A', 'Answers'), ('SA', 'Self Answers'), ('C', 'Comments'), ('SC', 'Self Comments'), ('V', 'Views'), ('PV', 'Post Votes'), ('QV', 'Question Votes'), ('AV', 'Answer Votes'), ('E', 'Edits'), ('P', 'Polls'), ('L', 'Login times')], max_length=2),
        ),
    ]
