# Generated by Django 3.2.6 on 2021-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_alter_badge_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correctAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='forExams',
            field=models.BooleanField(default=False),
        ),
    ]
