# Generated by Django 3.2.6 on 2021-10-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_alter_answer_correctanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'correctAnswer')},
        ),
    ]
