# Generated by Django 3.2.6 on 2021-10-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_answer_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='content.post'),
        ),
    ]
